exports.seed = function (knex, Promise) {
      return knex('clothing').insert([
         {
         id: 181,
         size_id: 36,
         style_id: 7,
         brand_id: 8,
         condition_id: 22,
         status_id: 51,
         title: 'Bobbles galore',
         description: 'I love this cutie little wooly, I am hiding this blurb in here because I do not think anyone will notice and I am rapidly running out of things to write as descriptions and filler text in all of these seeds. So this will do for now.',
         photo1: 'https://s-media-cache-ak0.pinimg.com/236x/8d/1e/b0/8d1eb00f62f53e74922c53d31d0110b1.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 182,
         size_id: 37,
         style_id: 7,
         brand_id: 9,
         condition_id: 22,
         status_id: 51,
         title: 'Owl-ove you!',
         description: 'Team up this jumper with a heavy denim skirt or pants and your bubby will be warm and snuggled up all day. The sleeves and cuffs on this are a little dis-coloured. The owls though are too lovely to ignore, so add this to the basket today.',
         photo1: 'https://s-media-cache-ak0.pinimg.com/736x/01/63/ee/0163eefda3146ef5ef111e8893ca3810.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 183,
         size_id: 32,
         style_id: 7,
         brand_id: 10,
         condition_id: 23,
         status_id: 51,
         title: 'Hipster as!',
         description: 'With this, your littlie will be the best dressed! So adorable. We love mini versions of the grown-up styles that we all love. This is just begging you to get larger ones and take family photo to embarrass them with at their 21st birthday.',
         photo1: 'https://ae01.alicdn.com/kf/HTB15ZjwIFXXXXcqXVXXq6xXFXXXB/New-2015-autumn-winter-sweater-children-clothing-font-b-baby-b-font-font-b-boys-b.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 184,
         size_id: 33,
         style_id: 7,
         brand_id: 1,
         condition_id: 23,
         status_id: 51,
         title: 'Starry days',
         description: 'Strong colours, it is so nice to see a little jumper that does not follow the pattern of pale and pastel. This is a bold design for a bold bubby. If your little one knows how to make an entrance then this is the one for you!',
         photo1: 'https://ae01.alicdn.com/kf/HTB1cvhxHXXXXXaLapXXq6xXFXXX4/2015-trend-children-clothing-baby-boy-knitwear-sweaters.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 185,
         size_id: 34,
         style_id: 7,
         brand_id: 2,
         condition_id: 24,
         status_id: 51,
         title: 'A Goldilocks favourite',
         description: 'This bear face is too cute. Your baby-bear will be rugged up and cosy in this little number. It is almost oversized so will look super cute over leggings, or rugged and tough (can a face that cute be tough?) over jeans.',
         photo1: 'http://www.seedheritage.com/dw/image/v2/AAZI_PRD/on/demandware.static/-/Sites-seed-master-catalog/en_AU/v1496616663890/images/4043008-se/seed-4043008-cm-v1.jpg?sw=232&sh=232&sm=fit',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 186,
         size_id: 35,
         style_id: 7,
         brand_id: 3,
         condition_id: 21,
         status_id: 51,
         title: 'Toggly goodness',
         description: 'This little button up jersey is perfect for even the coldest days. Thick and warm, but is a darker shade of cream than it looks in the photo. It is fairly small in size for best suited for little bubbies. Great over layer.',
         photo1: 'https://s-media-cache-ak0.pinimg.com/236x/f9/f9/5b/f9f95bf306cfdc2f88a6234cb87fef88.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 187,
         size_id: 36,
         style_id: 7,
         brand_id: 4,
         condition_id: 24,
         status_id: 51,
         title: 'Cabled goodness',
         description: 'Perfect for your little outdoors bubba. The bold colours on this are lovely and strong. Ideal for the active little one in your life. This is a gorgeous thick knitted top, so will be super warm for those beach day strolls.',
         photo1: 'https://www.target.com.au/medias/static_content/product/images/grid/02/45/A1060245.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 188,
         size_id: 37,
         style_id: 7,
         brand_id: 5,
         condition_id: 24,
         status_id: 51,
         title: 'Lizard love',
         description: 'If you have a little monster in your life, it is important to dress them accordingly. This adorable little hoody with the lizard or dinosaur spines on the hood is super cute. Lovely bright colours. It is preloved and was obviously a favourite, but still has lots of love to give.',
         photo1: '/images/hoody_1.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 189,
         size_id: 32,
         style_id: 7,
         brand_id: 6,
         condition_id: 21,
         status_id: 51,
         title: 'Red pullover',
         description: 'Great bright hoody, it will go with anything because there is no pattern or conflicting design. Making it great for a capsule wardrobe. This top comes up slightly small so best for little bubbies. Would look so great teamed with skirt, jeans or funky little pants.',
         photo1: '/images/hoody_2.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 190,
         size_id: 33,
         style_id: 7,
         brand_id: 7,
         condition_id: 23,
         status_id: 51,
         title: 'Zip up',
         description: 'Easy and practical this is a great choice for little ones who are still learning to regulate. It can be undone to allow a little more air and zipped up if the temps drop or you need to do outside. Perfect for wrapping up warm. Such good condition.',
         photo1: '/images/hoody_3.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 191,
         size_id: 34,
         style_id: 7,
         brand_id: 8,
         condition_id: 23,
         status_id: 51,
         title: 'Panda cuteness',
         description: 'OMG! This panda faced jersey is to die for, its got such a cute and trendy edge. We love this designer, their kids wear is always the best quality and New Zealand made to boot - you do not get much better than that. Get in quick!',
         photo1: 'https://johnlewis.scene7.com/is/image/JohnLewis/003102461?$prod_main$',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 192,
         size_id: 34,
         style_id: 7,
         brand_id: 9,
         condition_id: 23,
         status_id: 51,
         title: 'Fluffy-butt!',
         description: 'You will never want to stop cuddling your fluffy-little bundle once they are wrapped up in this top. It will be gorgeous and super warm, perfect for days out in the buggy. Super soft, it does have a little mark near the neck, but it does not detract.',
         photo1: 'https://s-media-cache-ak0.pinimg.com/originals/c4/dd/4d/c4dd4df1cfa175be035ac5e5decc7d6d.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 193,
         size_id: 35,
         style_id: 7,
         brand_id: 10,
         condition_id: 23,
         status_id: 51,
         title: 'Girls rock!',
         description: 'They can wear grey too Celleste is rocking this preloved hoody. Proof that it does not have to be pink to be girly! We love unisex clothing because it keeps the options fresh for all our lovely members. Get this hoody before its gone. Make it your style by matching it with accessories you love.',
         photo1: 'https://img1.etsystatic.com/139/0/12563269/il_fullxfull.933678237_ej3l.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 194,
         size_id: 36,
         style_id: 9,
         brand_id: 1,
         condition_id: 23,
         status_id: 51,
         title: 'Noob bib',
         description: 'You can not help but find this totally adorable, even if my seed writing abilities have deserted me, but forgive me and hire this anyway - slightly marked in place ... well it is a bib?!',
         photo1: 'http://kidslovethisstuff.com/wp-content/uploads/2014/06/Geek-baby-clothes-NooB-baby-feeding-bib.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 195,
         size_id: 37,
         style_id: 9,
         brand_id: 2,
         condition_id: 23,
         status_id: 51,
         title: 'Meow town',
         description: 'Kitty tights for the win, and the winter! Ha you can have the cutest knees in town with these puurrrrfect tights. Forgive my poor puns I have been writing this crap for 18 hours.',
         photo1: 'http://catbuddydirect.com/wp-content/uploads/2016/12/Autumn-Winter-Girls-Tights-Kawaii-Kids-Splice-Thick-Stockings-Baby-Cat-Elastic-Cotton-Knitwear-Cute-Pantyhose-1.jpg',
         photo2: '/images/photo_2.svg'
         },

         {
         id: 196,
         size_id: 36,
         style_id: 4,
         brand_id: 3,
         condition_id: 22,
         status_id: 51,
         title: 'Vroom vroom',
         description: 'Awesome little t-shirt is seriously adorable. Give your little bundle of joy a rev up with this cute little T, its lovely and soft and perfect for summer days. Layered with a hoody or other outer layer is will be great in to autumn as well.',
         photo1: '/images/tshirt_1.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 197,
         size_id: 35,
         style_id: 4,
         brand_id: 4,
         condition_id: 22,
         status_id: 51,
         title: 'Little cutie',
         description: 'The title says it all, we are in love with the adorable embroidery on this top. The leaves are starting to fray in a couple of places but there is heaps of love left in this navy blue top. The colours are great and the fit is on the larger side.',
         photo1: '/images/tshirt_2.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 198,
         size_id: 34,
         style_id: 4,
         brand_id: 5,
         condition_id: 22,
         status_id: 51,
         title: 'Acute shirt',
         description: 'Geek humour at its best. Bright and cheerful yellow is perfect for this funny little top. We imagine it teamed up with jeans or a denim skirt for a mini-geek appearance. Would be great for either a boy or a girl and is in near new condition.',
         photo1: '/images/tshirt_4.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 199,
         size_id: 33,
         style_id: 4,
         brand_id: 6,
         condition_id: 22,
         status_id: 51,
         title: 'I won!',
         description: 'Funny little t-shirt, was too cute to ignore. It has a couple of little marks on it, but is still in good condition. It is not a very thick fabric, so might be best used as a layer with other clothing items.',
         photo1: '/images/tshirt_3.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 200,
         size_id: 31,
         style_id: 4,
         brand_id: 7,
         condition_id: 21,
         status_id: 51,
         title: 'Munch monkey',
         description: 'The yellow always makes us smile, such a sunny bright top. Cute printed monkey on the front, the paint is starting to crack and peel in places. Good size, it will fit most babies in the size range. Great for summer days.',
         photo1: '/images/tshirt_5.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 201,
         size_id: 31,
         style_id: 4,
         brand_id: 8,
         condition_id: 23,
         status_id: 51,
         title: 'One-derful',
         description: 'Oh it is so punny! If your bub got a birthday coming up... This is the perfect shirt to eat cake in. Lovely quality from this high street retailer, looks like its hardly been worn so we are putting this on our wish list for warmer months.',
         photo1: '/images/tshirt_6.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 202,
         size_id: 33,
         style_id: 4,
         brand_id: 9,
         condition_id: 23,
         status_id: 51,
         title: 'Only child',
         description: 'Cute little top with a frill. The date does kind of date the t-shirt but the added frill made it too special to ignore. The longer layer means it would work well as a little dress too it layered with thick tights or leggings.',
         photo1: '/images/tshirt_7.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 203,
         size_id: 36,
         style_id: 4,
         brand_id: 10,
         condition_id: 24,
         status_id: 51,
         title: 'Eat, Sleep ...',
         description: 'Gym junkies... this is for you! If you want to raise your self a little powerhouse baby, get your sweat on by racing to be first to borrow this t-shirt. It is slightly small in size, so might be best for little bubbas.',
         photo1: '/images/tshirt_8.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 204,
         size_id: 36,
         style_id: 4,
         brand_id: 10,
         condition_id: 24,
         status_id: 51,
         title: 'Little Sister',
         description: 'I love seeing darker colours on girls. It does not have to be pink to be super cute. This top is a little stretched but the print is in really good condition and there is still a lot of wear to be had from this little number.',
         photo1:'http://www.carters.com/dw/image/v2/AAMK_PRD/on/demandware.static/-/Sites-carters_master_catalog/default/dw8fc630f6/hi-res/235G900_Default.jpg?sw=244',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 205,
         size_id: 36,
         style_id: 4,
         brand_id: 10,
         condition_id: 24,
         status_id: 51,
         title: 'Tui cute!',
         description: 'This designer t-shirt is made of thick luxury jersey knit fabric and will fit all sizes. There is lovely print on the front which is cracked but not peeling, its been very well made and will be warm even if not layered with anything else.',
         photo1: 'https://ih0.redbubble.net/image.363492089.3102/ra%2Cbaby_tee%2Cx520%2Cbaby_blue%2Cfront-pad%2C420x460%2Cf8f8f8.lite-1u4.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 206,
         size_id: 32,
         style_id: 1,
         brand_id: 1,
         condition_id: 24,
         status_id: 51,
         title: 'Dungarees',
         description: 'Do these ever go out of fashion? We love these little dungarees, they would make any kid look ready to take on the world. If clothing could shout, these would shout high energy. Perfect for your little one if they never sit still!',
         photo1: 'http://media.jojomamanbebe.com/media/catalog/product/cache/1/small_image/300x/c75b604ff82387216c03b93a91337e7c/d/2/d2783red_2.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 207,
         size_id: 32,
         style_id: 1,
         brand_id: 2,
         condition_id: 21,
         status_id: 51,
         title: 'Awesome cord',
         description: 'Great colour - classic beige with the preppy little turn up, make these pants a winner in our book. Team it up with blues and reds for a strong distinct look. Dressed to impressed you are ready, and set... Time to take on the siblings.',
         photo1: 'http://www.crecerfeliz.es/var/ezflow_site/storage/images/el-bebe/buenas-ideas/moda-primeros-meses/pantalon-bebe-chicco/2711565-1-esl-ES/pantalon-bebe-chicco_reference.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 208,
         size_id: 34,
         style_id: 1,
         brand_id: 3,
         condition_id: 22,
         status_id: 51,
         title: 'Leopard print love!',
         description: 'Seriously who can resist these. We love this print! The gold is starting to wear in places, but they are in great condition and made of a really lovely warm jersey fabric. Take these home today, because they wont last long this style is super popular.',
         photo1: 'http://do8c9c0qrr1ax.cloudfront.net/sys-master/images/hd8/hc7/9089997668382/649043_001.jpg_BNLWF_medium',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 209,
         size_id: 35,
         style_id: 1,
         brand_id: 4,
         condition_id: 23,
         status_id: 51,
         title: 'Foot coverage',
         description: 'We love these little leggings, the feet enclosed means baby will stay cosy and warm all the time. Perfect for little ones who are still learning to regulate. The grey of these is a little faded in appearance but otherwise in really good condition.',
         photo1: 'http://do8c9c0qrr1ax.cloudfront.net/sys-master/images/he3/h5f/9073076076574/538414_001.jpg_BNLWF_medium',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 210,
         size_id: 36,
         style_id: 1,
         brand_id: 5,
         condition_id: 22,
         status_id: 51,
         title: 'Homemade!',
         description: 'Holy moly! This fabric is so gorgeous. Totally on trend with the slightly baggy style. The elastic is soft and very stretchy, the seamstress who put these together really knows there craft. They are so lovely - thank you talented person for sharing them with us!',
         photo1: 'https://s-media-cache-ak0.pinimg.com/736x/38/c3/96/38c3966440cc204892b23c20837dd27c.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 211,
         size_id: 32,
         style_id: 1,
         brand_id: 6,
         condition_id: 23,
         status_id: 51,
         title: 'Raindrops',
         description: 'Awesome little track suit bottoms with lots of room for a nappy. Thick jersey so will be lovely and warm. They are very stretchy and in perfect condition. IF I could get away with wearing this style of pants every day I would... you know you would too.',
         photo1: 'https://4.imimg.com/data4/UT/TO/MY-2190204/1-250x250.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 212,
         size_id: 33,
         style_id: 1,
         brand_id: 7,
         condition_id: 24,
         status_id: 51,
         title: 'Jeans forever',
         description: 'Jeans are just the best, is there anything that they do not go with? I am sure you could wear jeans almost every day, and still be stylee and well dressed. These are cute and perfect for keeping your little one warm on colder days. Add them to your wardrobe staples now!',
         photo1: '/images/pants_1.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 213,
         size_id: 34,
         style_id: 1,
         brand_id: 8,
         condition_id: 23,
         status_id: 51,
         title: 'I <3 Jeans',
         description: 'Jeans are just the best, is there anything that they do not go with? I am sure you could wear jeans almost every day, and still be stylee and well dressed. These are cute and perfect for keeping your little one warm on colder days. Add them to your wardrobe staples now!',
         photo1: '/images/pants_2.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 214,
         size_id: 35,
         style_id: 1,
         brand_id: 9,
         condition_id: 21,
         status_id: 51,
         title: 'Baa-utiful',
         description: 'These sheepy leggings are too cute! I love them, but might get funny looks if I attempt to get a pair in grown up size. However I do not think you could possibly be in a bad mood when you were wearing them so maybe I will get some for everyone I know! Yay! For cute critters on leggings',
         photo1: '/images/pants_3.png',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 215,
         size_id: 35,
         style_id: 1,
         brand_id: 9,
         condition_id: 21,
         status_id: 51,
         title: 'Frilly bum',
         description: 'Just the thought of a cute little frilly bum popping out from the bottom of a skirt makes me giggle. So of course these would be my must have for colder days. There is a small pull in the toe area, but once you have little slippers on no one will be any the wiser.',
         photo1: '/images/pants_4.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 216,
         size_id: 35,
         style_id: 1,
         brand_id: 9,
         condition_id: 21,
         status_id: 51,
         title: 'Foxy!',
         description: 'Just the thought of a cute little foxy bum popping out from the bottom of a skirt or long jumper makes me giggle. The bold colour of these is a perfect match to a strong personality. There is a small pull in the toe area, but once you have little slippers on no one will be any the wiser.',
         photo1: '/images/pants_5.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 217,
         size_id: 35,
         style_id: 1,
         brand_id: 9,
         condition_id: 21,
         status_id: 51,
         title: 'Jeans for the win',
         description: 'Jeans are just the best, is there anything that they do not go with? I am sure you could wear jeans almost every day, and still be stylee and well dressed. These are cute and perfect for keeping your little one warm on colder days. Add them to your wardrobe staples now!',
         photo1: '/images/pants_6.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 218,
         size_id: 35,
         style_id: 1,
         brand_id: 9,
         condition_id: 21,
         status_id: 51,
         title: 'Legs forever',
         description: 'Is there anything these leggings wont go with? Team them with pastels or bold colours for a brilliant look no matter what the day or style. The grey on these is a little faded but really the quality speaks for it self, the warm, thick fabric is perfect for little legs.',
         photo1: '/images/pants_7.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 219,
         size_id: 35,
         style_id: 1,
         brand_id: 9,
         condition_id: 21,
         status_id: 51,
         title: 'Lazy sailing days',
         description: 'Live by a lake? Ocean? River? Really even if you just own a paddling pool these are still adorable. The grey on these is such a great neutral colour, it will go with anything and the sailing boats are too cute. Really the quality speaks for it self, the warm, thick fabric is perfect for little legs.',
         photo1: '/images/pants_8.jpg',
         photo2: '/images/photo_2.svg'
         },
         {
         id: 220,
         size_id: 35,
         style_id: 1,
         brand_id: 9,
         condition_id: 21,
         status_id: 51,
         title: 'Anchors away',
         description: 'Great little jeans for a bigger bub, they are long in the legs and the fold up means there is heaps of room to grow into them. The cute pattern is cool too as it adds a point of difference from straight up jeans. If you are predicting a growth spurt, add these to the basket now!',
         photo1: '/images/pants_9.jpg',
         photo2: '/images/photo_2.svg'
         }
      ])
   }
