
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('clothing').del()
    .then(function () {
      return knex('clothing').insert([
        {
          id: 100,
          size_id: 32,
          style_id: 8,
          brand_id: 5,
          condition_id: 22,
          status_id: 51,
          title:'If you can read this!',
          description: 'Very cute neutral babygrow, in nice condition.  Please note there is slight pilling on rear. Fit  comes up slightly small. Suitable as an under-layer or for use in warmer weather.',
          photo1: '/images/babyg_1.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 120,
          size_id: 35,
          style_id: 8,
          brand_id: 2,
          condition_id: 21,
          status_id: 51,
          title:'Silent night',
          description: 'Amazing quality, gold text slightly glittery. Perfect little christmas outfit. Looks like its never been worn.',
          photo1: '/images/babyg_2.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 121,
          size_id: 34,
          style_id: 8,
          brand_id: 1,
          condition_id: 24,
          status_id: 51,
          title:'Yoga guru',
          description: 'So adorable! The best choice for all you gym mums out there in pretty good condition.  Please note there is a tiny stain at the neck. Seems longer than other onesie suits. Be a great summer option.',
          photo1: '/images/babyg_3.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 122,
          size_id: 31,
          style_id: 8,
          brand_id: 5,
          condition_id: 22,
          status_id: 51,
          title:'Peachy petite',
          description: 'Very peachy babygrow, in nice condition. Please note there is slight pilling on rear. Fit comes up slightly small. Thick cotton - lovely for colder days.',
          photo1: 'https://www.oliverbonas.com/static/media/catalog/product/c/1/c1074512_oliver-bonas_gift_ma-petite-baby-grow.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 123,
          size_id: 35,
          style_id: 8,
          brand_id: 3,
          condition_id: 22,
          status_id: 51,
          title:'9 months',
          description: 'So funny! What a talking point -  in nice condition. Has small dye mark on cuffs. Fit comes up larger than expected. Would look super cute with jeans and a hoody for winter.',
          photo1: 'http://cdn.shopify.com/s/files/1/1140/3192/products/2012_baby_babygrow_just-done-9-months-inside_lack-_-white_1_grande.png?v=1458568176',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 124,
          size_id: 31,
          style_id: 8,
          brand_id: 5,
          condition_id: 22,
          status_id: 51,
          title:'Dressed to impress',
          description: 'Special occasion coming up? Dress your premmy guest of honour in this. Please note it is more creamy coloured than it is white. Fit best for small prems. Suitable for even black tie events.',
          photo1: 'https://cdn.childrensalon.com/media/catalog/product/cache/0/image/1000x1000/9df78eab33525d08d6e5fb8d27136e95/t/h/the-tiny-universe-boys-ivory-the-velvet-tuxedo-babygrow-72320-fb0c4ee943c42ac844df78ee1cd62ba6deb25710.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 125,
          size_id: 35,
          style_id: 8,
          brand_id: 2,
          condition_id: 21,
          status_id: 51,
          title:'When I grow up',
          description: ' ... A spread-operator? Somewhat ambiguous but conversation starting suit. There is a small amount of stretching around the neck, but it still fits snuggly and looks gorgeous on. Short sleeves make it better for warmer months.',
          photo1: 'https://cdn.notonthehighstreet.com/system/product_images/images/001/155/842/original_personalised-baby-grow-when-i-grow-up.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 126,
          size_id: 37,
          style_id: 3,
          brand_id: 5,
          condition_id: 23,
          status_id: 51,
          title:'Tweedy pie',
          description: 'Very grown up little dress, in really nice condition. Please note there is slight pilling on rear. Fit comes up slightly small. Suitable as a warm layer or for use in colder weather.',
          photo1: '/images/dress_1.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 127,
          size_id: 35,
          style_id: 3,
          brand_id: 3,
          condition_id: 21,
          status_id: 51,
          title:'I spotted it first!',
          description: 'Perfect for easy summer afternoons, this breezy spotted print dress is crafted in lightweight jersey and features a coordinating nappy cover. Please note there is a grass stain near the hem.',
          photo1: '/images/dress_2.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 128,
          size_id: 37,
          style_id: 3,
          brand_id: 5,
          condition_id: 22,
          status_id: 51,
          title:'Pocket of perfect',
          description: 'Navy and almost nautical, this striped dress is fairly lightweight jersey and features buttons that undo. Please note there is a pink mark near the pocket',
          photo1: '/images/dress_3.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 129,
          size_id: 32,
          style_id: 3,
          brand_id: 3,
          condition_id: 21,
          status_id: 51,
          title:'Summer stripes',
          description: 'Great for warm summer afternoons, or layered with leggings and a long sleeve t-shirt for when its cooler. Please note the elastic on the waste is a little worn, so it fits loosely, great for littlies who do not like being too wrapped up.',
          photo1: '/images/dress_4.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 130,
          size_id: 30,
          style_id: 8,
          brand_id: 3,
          condition_id: 21,
          status_id: 51,
          title:'Rainbows for the win',
          description: 'Long sleeved suit, that seems narrow. Lovely thick jersey, so your little rainbow can be as warm as toast! Room to grow if your bubba is going to be tall. Really impressed by the condition of this item.',
          photo1: 'https://littlepeagreen.files.wordpress.com/2012/04/frugi_rainbow_spot-babygrow-2.png',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 131,
          size_id: 30,
          style_id: 8,
          brand_id: 3,
          condition_id: 21,
          status_id: 51,
          title:'Ute will love this!',
          description: 'Little blue VW combie on the front. Hand sewn by a boutique supplier. Very cute, you can just tell the love that goes into creating these little NZ made vests. A great addition to you little ones wardrobe.',
          photo1: 'https://cdn.notonthehighstreet.com/system/product_images/images/000/491/279/original_Blue_campervan_vest.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 132,
          size_id: 34,
          style_id: 8,
          brand_id: 3,
          condition_id: 21,
          status_id: 51,
          title:'Pink geek',
          description: 'Oh my goodness so pink, honestly the most adorable thing I have seen in ages. It does have a little hole in the back but otherwise in great condition. If your little one knows how to make a statement then this is the outfit for you!',
          photo1: 'https://s3-eu-west-1.amazonaws.com/images.linnlive.com/4a3fc06eb1b04726bf024759db185f2f/b82257af-c06c-4669-bd60-949786611550.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 133,
          size_id: 37,
          style_id: 8,
          brand_id: 3,
          condition_id: 21,
          status_id: 51,
          title:'Maths Nerd',
          description: 'I do not think you have to be a nerd to love this onesie. Or to get the joke... This top is a lovely soft shade of blue and feels like brushed jersey cotton. The paint has chipped off the poppers, which is not noticeable when pants or skirt are added.',
          photo1: 'https://images-na.ssl-images-amazon.com/images/I/51OKFQZff6L._AC_UL320_SR244,320_.jpg',
          photo2: ''
        },
        {
         id: 134,
         size_id: 35,
         style_id: 7,
         brand_id: 8,
         condition_id: 21,
         status_id: 51,
         title: 'Son Goku Pyjamas'
         description: '(Dragon) Ball your little one up in this super cute onesie pyjama set inspired by the hit anime series, Dragon Ball Z. Summer weight light cotton is ideal for keeping your little Super Saiyan comfy over the warmer months of the year.',
         photo1: 'https://ae01.alicdn.com/kf/HTB1xxVoLFXXXXXQXXXXq6xXFXXXf/Romper-for-Children-Cloak-Romper-font-b-baby-b-font-font-b-goku-b-font-costume.jpg',
         photo2: '/images/photo_2.svg'
        },
        {
         id: 135,
         size_id: 34,
         style_id: 7,
         brand_id: 9,
         condition_id: 22,
         status_id: 51,
         title: 'Otterly Adorable',
         description: 'This baby unisex pyjama set is just so otterly cute! Crafted from a super soft cotton jersey the set consists of a scoop neck raglan top with cute otter print and matching pants with elasticised waistband',
         photo1: 'http://www.peteralexander.co.nz/PJ/images/productsnz/large/854129_paleblue_l_nz.jpg'
         photo2: '/images/photo_2.svg'
        },
        {
         id: 136,
         size_id: 33,
         style_id: 7,
         brand_id: 9,
         condition_id: 21,
         status_id: 51,
         title: 'Dinosaur PJ Set',
         description: 'Your baby will dream of playing dinosaurs in this cute Peter Alexander pyjama set. Crafted from a comfy cotton jersey fabric it consists of a scoop neck tee with placement dinosaur print, matching pants with draw cord.',
         photo1: 'http://www.peteralexander.co.nz/PJ/images/productsnz/medium/853960_blue_m_nz.jpg'
         photo2: '/images/photo_2.svg'
       },
       {
         id: 137,
         size_id: 33,
         style_id: 7,
         brand_id: 9,
         condition_id: 22,
         status_id: 51,
         title: 'Teddy Bear Dressing Gown',
         description: 'The Peter Alexander best selling teddy gown now comes in a perfect tiny version for baby girls! Crafted from a super soft polyester fabric designed for daywear this baby gown features penny logo and cuffed built in sleeves for ultimate comfort.',
         photo1: 'http://www.peteralexander.com.au/PJ/images/products/large/853942_grey_l.jpg',
         photo2: '/images/photo_2.svg'
       },
       {
         id: 138,
         size_id: 35,
         style_id: 7,
         brand_id: 2,
         condition_id: 22,
         status_id: 51,
         title: 'Bearly sleepy',
         description: 'Your little one will snuggle up to sweet dreams in this matching flannel pyjama set that features playful prints for an adorable bedtime look. Cotton, button down front with elastic waistband pants.',
         photo1: 'http://www.kmart.co.nz/wcsstore/Kmart/images/ncatalog/f/0/67286270-1-f.jpg',
         photo2: '/images/photo_2.svg'
       },
       {
         id: 139,
         size_id: 33,
         style_id: 7,
         brand_id: 2,
         condition_id: 23,
         status_id: 51,
         title: 'Batman All-in-one',
         description: 'Cosy and comfy, this bodysuit is a great pick for your little dark knight for a great nights sleep. Cotton and viscose, crew neck, long sleeves, front zipper and ribbed cuffs. Small stain on front.',
         photo1: 'http://www.kmart.co.nz/wcsstore/Kmart/images/ncatalog/f/8/67353538-1-f.jpg',
         photo2: '/images/photo_2.svg'
       },
       {
         id: 140,
         size_id: 33,
         style_id: 7,
         brand_id: 2,
         condition_id: 22,
         status_id: 51,
         title: 'Cloud nine',
         description: 'Featuring a simple repeating cloud pattern, this cute sleepbag will keep your little one warm and comfy as they slip away into sweet slumber. Cotton and elastine, long sleeved with front zipper opening.',
         photo1: 'http://www.kmart.co.nz/wcsstore/Kmart/images/ncatalog/f/4/67387854-1-f.jpg',
         photo2: '/images/photo_2.svg'
       },
       {
         id: 141,
         size_id: 33,
         style_id: 7,
         brand_id: 2,
         condition_id: 21,
         status_id: 51,
         title: 'Milk & Cookies',
         description: 'Featuring adorable prints and a comfortable fit, this sleepsuit is a great pick for sleep time for your little one.  Cotton and elastine, long sleeved with front zipper opening and folded cuffs',
         photo1: 'http://www.kmart.co.nz/wcsstore/Kmart/images/ncatalog/f/8/67246168-1-f.jpg',
         photo2: '/images/photo_2.svg'
       },
       {
         id: 142,
         size_id: 34,
         style_id: 7,
         brand_id: 1,
         condition_id: 22,
         status_id: 51,
         title: 'Hello World',
         description: 'Hippo + Friends Baby Infant Envelope All-in-One. Hard wearing and warm, this cotton all-in-one is a stunning gender-neutral navy blue and available in a variety of sizes (see our other listings)',
         photo1: 'http://demandware.edgesuite.net/aawo_prd/on/demandware.static/-/Sites-twl-master-catalog/default/dw8479dc2b/99/a7/R2181368_00.jpg',
         photo2: '/images/photo_2.svg'
       },
       {
         id: 143,
         size_id: 35,
         style_id: 7,
         brand_id: 1,
         condition_id: 21,
         status_id: 51,
         title: 'Teepee Pyjama Onesie',
         description: 'Hippo + Friends Baby Boy All Over Print All-in-One. Warm wearing fleece, ideal for keeping your little one toasty warm on long winter nights. Cotton with zipper front, opening all the way to the toes.',
         photo1: 'http://demandware.edgesuite.net/aawo_prd/on/demandware.static/-/Sites-twl-master-catalog/default/dwf3f0aec4/1e/e2/R2160595_00.jpg',
         photo2: '/images/photo_2.svg'
       },
       {
          id: 144,
          size_id: 34,
          style_id: 8,
          brand_id: 2,
          condition_id: 23,
          status_id: 51,
          title: 'Hi-top canvas shoes',
          description: 'Featuring a hip high top design, these canvas shoes are a smart pick for your little one to team with a pair of cargo pants and a casual tee. Velco is a little tired but still works',
          photo1: 'http://www.kmart.co.nz/wcsstore/Kmart/images/ncatalog/f/1/67339501-1-f.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 145,
          size_id: 34,
          style_id: 8,
          brand_id: 2,
          condition_id: 21,
          status_id: 51,
          title: 'Pull-on boots',
          description: 'Designed with a soft footbed and classic polyurethane uppers, these pull on boots are a comfy and stylish pick for your little one to sport on outings. Synthetic with elastic gussets',
          photo1: 'http://www.kmart.co.nz/wcsstore/Kmart/images/ncatalog/f/6/67423996-1-f.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 146,
          size_id: 32,
          style_id: 8,
          brand_id: 2,
          condition_id: 21,
          status_id: 51,
          title: 'Soft Sole Novelty Slippers',
          description: 'Styled with cute prints on the upper and a soft sole, these slippers will look adorable on your baby and offer a comfy fit. In great near-new condition',
          photo1: 'http://www.kmart.co.nz/wcsstore/Kmart/images/ncatalog/f/2/67292912-1-f.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 147,
          size_id: 35,
          style_id: 8,
          brand_id: 9,
          condition_id: 21,
          status_id: 51,
          title: 'Ariel Baby Shoes',
          description: 'With natural butter-soft, breathable leather, and flexible soled shoes, each step for your baby is as comfortable as the first. The flexible soles have traction inserts, which help to provide grip and confidence for new walkers.',
          photo1: 'https://cdn.shopify.com/s/files/1/1995/1429/products/ariel_1024x1024@2x.png?v=1495003312',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 148,
          size_id: 37,
          style_id: 8,
          brand_id: 9,
          condition_id: 22,
          status_id: 51,
          title: 'Sprinter Baby Shoes',
          description: 'No matter what adventure your little guy is on, these baby shoes are sure to keep up! With natural butter-soft, breathable leather, and flexible soled shoes, each step for your baby is as comfortable as the first. The flexible soles have traction inserts, which help to provide grip and confidence for new walkers.',
          photo1: 'https://cdn.shopify.com/s/files/1/1995/1429/products/sprinter_1024x1024@2x.jpg?v=1495320505',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 149,
          size_id: 34,
          style_id: 8,
          brand_id: 9,
          condition_id: 21,
          status_id: 51,
          title: 'Two Little Feet Sandals',
          description: 'These Silver cross over baby sandals by Two Little Feet are gorgeous. This summer have others look on in pure delight! Made from the softest of leathers, not only are these baby shoes designed for comfort and fit, but they look downright stylish on her feet!',
          photo1: 'https://cdn.shopify.com/s/files/1/1995/1429/products/18_clipped_rev_1_1024x1024@2x.png?v=1495775825',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 150,
          size_id: 35,
          style_id: 8,
          brand_id: 9,
          condition_id: 22,
          status_id: 51,
          title: 'Rosie Baby Shoes',
          description: 'These delicious baby girls soft pink boots will be the envy of everyone on the cooler days ahead! 100% leather upper featuring a soft touch velcro closure on the side. Traction inserts to provide grip on those slippery surfaces',
          photo1: 'https://cdn.shopify.com/s/files/1/1995/1429/products/rosie_1024x1024@2x.png?v=1495319717',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 151,
          size_id: 33,
          style_id: 8,
          brand_id: 7,
          condition_id: 21,
          status_id: 51,
          title: 'Pre-walker Mini Rainboot',
          description: 'These nylon rain booties will keep little baby feet warm and dry. Super easy to get on and off, with a soft sole perfect for babies who are not walking yet.',
          photo1: 'http://cottonon.com/on/demandware.static/-/Sites-cog-kids-master/default/dwb1fa7e04/760346/760346-01-3.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 152,
          size_id: 34,
          style_id: 8,
          brand_id: 7,
          condition_id: 23,
          status_id: 51,
          title: 'Pre-walker Moccasins',
          description: 'Our mini take on a classic driving moccasin is too cute we have added a pop of fun colour on the sole for extra fun. Sole is wearing slightly, but as these are pre-walker shoes, this should not affect their use.',
          photo1: 'http://cottonon.com/on/demandware.static/-/Sites-cog-kids-master/default/dwe933877e/760360/760360-01-2.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 153,
          size_id: 32,
          style_id: 8,
          brand_id: 2,
          condition_id: 21,
          status_id: 51,
          title: 'Furry booties',
          description: 'Your little ones tiny feet will stay warm and look adorable in these fur bootees that feature 3D bunny ears and embroidery face details. As-new condition',
          photo1: 'http://www.kmart.co.nz/wcsstore/Kmart/images/ncatalog/f/5/67401215-1-f.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 154,
          size_id: 35,
          style_id: 9,
          brand_id: 9,
          condition_id: 22,
          status_id: 51,
          title: 'Woolen Mittens',
          description: 'These merino wool mittens are best washed by hand washing in an approved wool detergent. Just squeeze lightly in the water and then rinse. Do not spin dry - lie flat to dry on a towel is best.',
          photo1: 'https://www.cosytoes.co.nz/ic/2016134785/merino%20wool%20mittens.1.1.JPG',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 155,
          size_id: 31,
          style_id: 9,
          brand_id: 2,
          condition_id: 21,
          status_id: 51,
          title: 'My First Baby Blanket',
          description: 'Your little one is precious! Keep them snug, and cuddly in this light blanket that features a super soft feel for their comfort. Cotton, size: 70cm x 90cm',
          photo1: 'http://www.kmart.com.au/wcsstore/Kmart/images/ncatalog/f/6/42448266-1-f.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 156,
          size_id: 32,
          style_id: 9,
          brand_id: 2,
          condition_id: 22,
          status_id: 51,
          title: 'Thumbless mittens',
          description: 'Keep those tiny little hands all warm and toasty in these cute, soft mittens. Made from cotten, safe to machine wash according to instructions on the care label',
          photo1: 'http://www.kmart.com.au/wcsstore/Kmart/images/ncatalog/f/5/67624065-1-f.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 157,
          size_id: 33,
          style_id: 9,
          brand_id: 2,
          condition_id: 22,
          status_id: 51,
          title: 'Pink baby hat',
          description: 'Designed from soft and stretchy fabric, these hats will keep your little one warm and cosy all day. Made from cotton and elastine, easy care, hard wearing and great for those cold winter days.',
          photo1: 'http://www.kmart.com.au/wcsstore/Kmart/images/ncatalog/f/8/67623938-1-f.jpg',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 158,
          size_id: 35,
          style_id: 9,
          brand_id: 6,
          condition_id: 24,
          status_id: 51,
          title: 'Puppy Dog Mittens',
          description: 'These super cute puppy dog mittens will keep those little hands toasty warm in the depths of winter. Stitching holding thumb on has slightly pulled, but should still work nicely.',
          photo1: 'https://www.kidrepublic.co.nz/images/300/388/aw17-m018.jpg?h=6442fbb8',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 159,
          size_id: 36,
          style_id: 9,
          brand_id: 6,
          condition_id: 22,
          status_id: 51,
          title: 'Acorn Panda Beanie',
          description: 'Gorgeous panda beanie gives your baby the cutest look for winter. Made from merino wool, this is sure to keep them toasty warm in style during the cooler months of the year.',
          photo1: 'https://www.kidrepublic.co.nz/images/300/388/aw17-h016.jpg?h=babebf34',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 160,
          size_id: 38,
          style_id: 9,
          brand_id: 6,
          condition_id: 21,
          status_id: 51,
          title: 'Toshi Butternut Beanie',
          description: 'Super cute beanie with ears. Your little one will look ultra stylish during winter this year. Made from 100% merino wool and in pristine condition.',
          photo1: 'https://www.kidrepublic.co.nz/images/300/388/w17-be-but-cre.jpg?h=2fe02d48',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 161,
          size_id: 32,
          style_id: 9,
          brand_id: 3,
          condition_id: 21-24,
          status_id: 51,
          title: 'Hooded towel',
          description: 'Comfy, super soft and absorbent this 100% cotton hooded towel is designed to keep baby warm, dry and happy at bath time. This hoodedtowel is the perfect gift for a newborn baby.',
          photo1: 'http://www.farmers.co.nz/INTERSHOP/static/WFS/Farmers-Shop-Site/-/Farmers-Shop/en_NZ/product/61/44/345/2/6144345_00_W460_H600.jpg?lastmodified=201610062200031',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 162,
          size_id: 31,
          style_id: 9,
          brand_id: 3,
          condition_id: 22,
          status_id: 51,
          title: 'Have a Whale of a Bathtime',
          description: 'The Babyhood Bath Support will bring the fun back into bathing your baby for you. No bending over the bath hurting your back and no more slippery fingers trying to hold and wash your baby at the same time.',
          photo1: 'http://www.farmers.co.nz/INTERSHOP/static/WFS/Farmers-Shop-Site/-/Farmers-Shop/en_NZ/product/61/38/213/1/6138213_00_W460_H600.jpg?lastmodified=201607082213022',
          photo2: '/images/photo_2.svg'
        },
        {
          id: 163,
          size_id: 31,
          style_id: 9,
          brand_id: 3,
          condition_id: 21,
          status_id: 51,
          title: 'Jolly Jumper Baby Bath',
          description: 'Enjoy bathing your baby with ease, with this medium-sized white baby bath. Hard wearing plastic. In excellent condition and commercially cleaned between hires.',
          photo1: 'http://www.farmers.co.nz/INTERSHOP/static/WFS/Farmers-Shop-Site/-/Farmers-Shop/en_NZ/product/51/33/088/2/resized_460x600.jpg?lastmodified=197001011200000',
          photo2: '/images/photo_2.svg'
        },
        {
         id: 164,
         size_id: 35,
         style_id: 2,
         brand_id: 3,
         condition_id: 21,
         status_id: 51,
         title: 'Denim dreams',
         description: 'Baby blue tiered skirt, perfect if you wants something with a little weight and warmth. Lovely fit, elastic not too tight so should fit all little ones for a good length of time. The flared design means little legs can still move freely.',
         photo1: '/images/skirt_1.jpg',
         photo2: '/images/photo_2.svg'
       },
       {
        id: 165,
        size_id: 37,
        style_id: 2,
        brand_id: 4,
        condition_id: 22,
        status_id: 51,
        title: 'Pink and Lacey',
        description: 'This is very cute. Like a little cheerleader skirt, but longer than it looks so will come down nicely over little legs. The flare on the cut means that there is still full movement for little legs. It seems like a winner all round.',
        photo1: '/images/skirt_2.jpg',
        photo2: '/images/photo_2.svg'
      },
      {
      id: 166,
      size_id: 36,
      style_id: 2,
      brand_id: 6,
      condition_id: 22,
      status_id: 51,
      title: 'Grey Floral',
      description: 'Can I have one of these? If your little one is getting a corporate role, this would be perfect for the boardroom. Super sweet, and lovely style and condition, this is made from premium fabric so is a great find for us.',
      photo1: '/images/skirt_3.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 167,
      size_id: 33,
      style_id: 2,
      brand_id: 8,
      condition_id: 22,
      status_id: 51,
      title: 'Jeans skirt',
      description: 'This is such a grown up style, its adorable and will look fab layered with pattered leggings. Maybe best suited to older bubs as the straight style might be a little restrictive if you have a little wriggler it might not be the best choice.',
      photo1: '/images/skirt_4.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 168,
      size_id: 36,
      style_id: 2,
      brand_id: 2,
      condition_id: 22,
      status_id: 51,
      title: 'Red pleats',
      description: 'This skirt is made of lovely thick cord material. So warm and cozy. This will be perfect layered over tights or leggings. It is in great condition and looks brand new, so grab it while its in!',
      photo1: 'https://www.polyvore.com/cgi/img-thing?.out=jpg&size=l&tid=373536',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 169,
      size_id: 37,
      style_id: 2,
      brand_id: 3,
      condition_id: 22,
      status_id: 51,
      title: 'Homemade with love',
      description: 'Gorgeous earthy colours, this has no brand because it has been hand made with love. The little black frill under the hem just adds a little bit of polish to this beautifully made skirt. So well made this will keep going for years.',
      photo1: 'http://farm3.static.flickr.com/2172/2258609457_778d56e3d9_o.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 170,
      size_id: 34,
      style_id: 2,
      brand_id: 4,
      condition_id: 22,
      status_id: 51,
      title: 'Super sweet',
      description: 'This little beauty is brand new, we had to cut the labels off! It will be the perfect addition to your babies wardrobe, suitable for all occasions. The pink details - the thread and pattern make it really unique and you guessed right, its super sweet.',
      photo1: 'https://ae01.alicdn.com/kf/HTB1O8EeIVXXXXcDXVXXq6xXFXXXg/2-6Y-Girls-light-Blue-font-b-Denim-b-font-font-b-skirts-b-font-font.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 171,
      size_id: 33,
      style_id: 2,
      brand_id: 5,
      condition_id: 21,
      status_id: 51,
      title: 'Pink magnolias',
      description: 'The softness of this fabric makes it drape and hang so well. It is in great condition with no obvious wear. The elastic is loose so not great if you have a tiny bub. There is a little hole (from the tag) in the side but you cant see it when its on.',
      photo1: 'http://www.carters.com/dw/image/v2/AAMK_PRD/on/demandware.static/-/Sites-carters_master_catalog/default/dw2131c5cb/hi-res/258G474_Default.jpg?sw=244',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 172,
      size_id: 37,
      style_id: 2,
      brand_id: 6,
      condition_id: 21,
      status_id: 51,
      title: 'Cute in the city',
      description: 'Ahh! I want one... so jealous. The silver rain drops and the double fabric layer make this a winner in all seasons. I wonder how hard it would be to make a matching version for mum? The drops are a little faded in places, but its to be expected, it will become a favourite, I guarantee!',
      photo1: 'https://luibelle.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/d/s/dsc_8435_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 173,
      size_id: 32,
      style_id: ,
      brand_id: 1,
      condition_id: 21,
      status_id: 51,
      title: 'Tropical Paradise',
      description: 'Sleeveless tropical dress with a cute little frill at the neck. In really gorgeous condition. The dress is on the larger size, so will fit a baby all the way through that next growth spurt.',
      photo1: 'http://nord.imgix.net/Zoom/18/_100916358.jpg?fit=fill&fm=jpg&dpr=2&h=368&w=240&q=30',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 174,
      size_id: 33,
      style_id: 3,
      brand_id: 2,
      condition_id: 21,
      status_id: 51,
      title: 'Totally tweet',
      description: 'The most adorable blue gingham dress with parrots around the hem, the embroidery is coming away in a few places but it does not detract from how gorgeous this is. The red ribbon on the hem finishes it perfectly. Matching elasticated underwear.',
      photo1: 'http://nord.imgix.net/Zoom/19/_101115879.jpg?fit=fill&fm=jpg&dpr=2&h=368&w=240&q=30',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 175,
      size_id: 34,
      style_id: 3,
      brand_id: 3,
      condition_id: 21,
      status_id: 51,
      title: 'So different',
      description: 'Very soft, feminine floral dress and vest in one. There is a little fraying on the frill around the neck. The colours of this are so gentle and warm. Very nice quality fabric, has washed really well and looks great.',
      photo1: 'https://s-media-cache-ak0.pinimg.com/736x/2d/7c/92/2d7c92e252257f3c5295c4a420839fad.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 176,
      size_id: 35,
      style_id: 3,
      brand_id: 4,
      condition_id: 21,
      status_id: 51,
      title: 'Chiffon flowers',
      description: 'Be better dressed than anyone else with this cute little dress. Aqua, teal and turquoise flowers, this is a real winner. Maybe best for special occasion, or any day for your little princess. The netting layer has worn so well - in awesome condition.',
      photo1: 'https://s.tea-global.net/mas_assets/cache/image/1/9/a/5/105055.Jpg',
      photo2: '/images/photo_2.svg'
      },
      id: 177,
      size_id: 34,
      style_id: 7,
      brand_id: 4,
      condition_id: 21,
      status_id: 51,
      title: 'Beary cute',
      description: 'Seriously adorable, it is not quite dress up, but close enough! Give your little bundle of joy some teddy love with this cute little bear jumper, its lovely and soft and super warm. Layered with a t-shirt it will make the perfect outfit.',
      photo1: '/images/jumper_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 178,
      size_id: 36,
      style_id: 3,
      brand_id: 5,
      condition_id: 21,
      status_id: 51,
      title: 'We recycle',
      description: 'Simply jealous! I love this dress so much I want one in my size. It is simple and perfect. Lemon yellow with the bicycle print is a winner. Soft cotton, it will need to be layered to keep bub warm.',
      photo1: 'https://s-media-cache-ak0.pinimg.com/236x/22/b8/50/22b850523d1b9b7021dfb2fc91a44407.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 179,
      size_id: 34,
      style_id: 7,
      brand_id: 6,
      condition_id: 21,
      status_id: 51,
      title: 'Ears a winner!',
      description: 'We changed the rules for this photo, because little Felix is the perfect model for this jumper. Who can resist? This is a great choice for boys and girls and will cause everyone to oooh and ahh and giggle over the awesome choice you made.',
      photo1: '/images/jumper_2.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 180,
      size_id: 35,
      style_id: 7,
      brand_id: 7,
      condition_id: 22,
      status_id: 51,
      title: 'Cosy stripes',
      description: 'The pink and grey combination is such a winner, it goes with everything, and makes a great over layer for keeping the chill out. It is knitted so super soft and stretchy and is in lovely condition. Make it yours today.',
      photo1: '/images/jumper_3.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 181,
      size_id: 36,
      style_id: 7,
      brand_id: 8,
      condition_id: 22,
      status_id: 51,
      title: 'Bobbles galore',
      description: 'I love this cutie little wooly, I'm hiding this blurb in here because I don't think anyone will notice and I am rapidly running out of things to write as descriptions and filler text in all of these seeds. So this will do for now.',
      photo1: 'https://s-media-cache-ak0.pinimg.com/236x/8d/1e/b0/8d1eb00f62f53e74922c53d31d0110b1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 182,
      size_id: 37,
      style_id: 7,
      brand_id: 9,
      condition_id: 22,
      status_id: 51,
      title: 'Owl-ove you!',
      description: 'Team up this jumper with a heavy denim skirt or pants and your bubby will be warm and snuggled up all day. The sleeves and cuffs on this are a little dis-coloured. The owls though are too lovely to ignore, so add this to the basket today.',
      photo1: 'https://s-media-cache-ak0.pinimg.com/736x/01/63/ee/0163eefda3146ef5ef111e8893ca3810.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 183,
      size_id: 32,
      style_id: 7,
      brand_id: 10,
      condition_id: 23,
      status_id: 51,
      title: 'Hipster as!',
      description: 'With this, your littlie will be the best dressed! So adorable. We love mini versions of the grown-up styles that we all love. This is just begging you to get larger ones and take family photo to embarrass them with at their 21st birthday.',
      photo1: 'https://ae01.alicdn.com/kf/HTB15ZjwIFXXXXcqXVXXq6xXFXXXB/New-2015-autumn-winter-sweater-children-clothing-font-b-baby-b-font-font-b-boys-b.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 184,
      size_id: 33,
      style_id: 7,
      brand_id: 1,
      condition_id: 23,
      status_id: 51,
      title: 'Starry days',
      description: 'Strong colours, it is so nice to see a little jumper that does not follow the pattern of pale and pastel. This is a bold design for a bold bubby. If your little one knows how to make an entrance then this is the one for you!',
      photo1: 'https://ae01.alicdn.com/kf/HTB1cvhxHXXXXXaLapXXq6xXFXXX4/2015-trend-children-clothing-baby-boy-knitwear-sweaters.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 185,
      size_id: 34,
      style_id: 7,
      brand_id: 2,
      condition_id: 24,
      status_id: 51,
      title: 'A Goldilocks favourite',
      description: 'This bear face is too cute. Your baby-bear will be rugged up and cosy in this little number. It is almost oversized so will look super cute over leggings, or rugged and tough (can a face that cute be tough?) over jeans.',
      photo1: 'http://www.seedheritage.com/dw/image/v2/AAZI_PRD/on/demandware.static/-/Sites-seed-master-catalog/en_AU/v1496616663890/images/4043008-se/seed-4043008-cm-v1.jpg?sw=232&sh=232&sm=fit',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 186,
      size_id: 35,
      style_id: 7,
      brand_id: 3,
      condition_id: 21,
      status_id: 51,
      title: 'Toggly goodness',
      description: 'This little button up jersey is perfect for even the coldest days. Thick and warm, but is a darker shade of cream than it looks in the photo. It is fairly small in size for best suited for little bubbies. Great over layer.',
      photo1: 'https://s-media-cache-ak0.pinimg.com/236x/f9/f9/5b/f9f95bf306cfdc2f88a6234cb87fef88.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 187,
      size_id: 36,
      style_id: 7,
      brand_id: 4,
      condition_id: 24,
      status_id: 51,
      title: 'Cabled goodness',
      description: 'Perfect for your little outdoors bubba. The bold colours on this are lovely and strong. Ideal for the active little one in your life. This is a gorgeous thick knitted top, so will be super warm for those beach day strolls.',
      photo1: 'https://www.target.com.au/medias/static_content/product/images/grid/02/45/A1060245.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 188,
      size_id: 37,
      style_id: 7,
      brand_id: 5,
      condition_id: 24,
      status_id: 51,
      title: 'Lizard love',
      description: 'If you have a little monster in your life, it is important to dress them accordingly. This adorable little hoody with the lizard or dinosaur spines on the hood is super cute. Lovely bright colours. It is preloved and was obviously a favourite, but still has lots of love to give.',
      photo1: '/images/hoody_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 189,
      size_id: 32,
      style_id: 7,
      brand_id: 6,
      condition_id: 21,
      status_id: 51,
      title: 'Red pullover',
      description: 'Great bright hoody, it will go with anything because there is no pattern or conflicting design. Making it great for a capsule wardrobe. This top comes up slightly small so best for little bubbies. Would look so great teamed with skirt, jeans or funky little pants.',
      photo1: '/images/hoody_2.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 190,
      size_id: 33,
      style_id: ,
      brand_id: 7,
      condition_id: 23,
      status_id: 51,
      title: 'Zip up',
      description: 'Easy and practical this is a great choice for little ones who are still learning to regulate. It can be undone to allow a little more air and zipped up if the temps drop or you need to do outside. Perfect for wrapping up warm. Such good condition.',
      photo1: '/images/hoody_3.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 191,
      size_id: 34,
      style_id: 7,
      brand_id: 8,
      condition_id: 23,
      status_id: 51,
      title: 'Panda cuteness',
      description: 'OMG! This panda faced jersey is to die for, its got such a cute and trendy edge. We love this designer, their kids wear is always the best quality and New Zealand made to boot - you do not get much better than that. Get in quick!',
      photo1: 'https://johnlewis.scene7.com/is/image/JohnLewis/003102461?$prod_main$',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 192,
      size_id: 34,
      style_id: 7,
      brand_id: 9,
      condition_id: 23,
      status_id: 51,
      title: 'Fluffy-butt!',
      description: 'You will never want to stop cuddling your fluffy-little bundle once they are wrapped up in this top. It will be gorgeous and super warm, perfect for days out in the buggy. Super soft, it does have a little mark near the neck, but it does not detract.',
      photo1: 'https://s-media-cache-ak0.pinimg.com/originals/c4/dd/4d/c4dd4df1cfa175be035ac5e5decc7d6d.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 193,
      size_id: 35,
      style_id: 7,
      brand_id: 10,
      condition_id: 23,
      status_id: 51,
      title: 'Girls rock!',
      description: 'They can wear grey too Celleste is rocking this preloved hoody. Proof that it does not have to be pink to be girly! We love unisex clothing because it keeps the options fresh for all our lovely members. Get this hoody before its gone. Make it your style by matching it with accessories you love.',
      photo1: 'https://img1.etsystatic.com/139/0/12563269/il_fullxfull.933678237_ej3l.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 194,
      size_id: 36,
      style_id: 9,
      brand_id: 1,
      condition_id: 23,
      status_id: 51,
      title: 'Noob bib',
      description: 'You can not help but find this totally adorable, even if my seed writing abilities have deserted me, but forgive me and hire this anyway - slightly marked in place ... well it is a bib?!',
      photo1: 'http://kidslovethisstuff.com/wp-content/uploads/2014/06/Geek-baby-clothes-NooB-baby-feeding-bib.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 195,
      size_id: 37,
      style_id: 9,
      brand_id: 2,
      condition_id: 23,
      status_id: 51,
      title: 'Meow town',
      description: 'Kitty tights for the win, and the winter! Ha you can have the cutest knees in town with these puurrrrfect tights. Forgive my poor puns I have been writing this crap for 18 hours.',
      photo1: 'http://catbuddydirect.com/wp-content/uploads/2016/12/Autumn-Winter-Girls-Tights-Kawaii-Kids-Splice-Thick-Stockings-Baby-Cat-Elastic-Cotton-Knitwear-Cute-Pantyhose-1.jpg',
      photo2: '/images/photo_2.svg'
      },

      {
      id: 196,
      size_id: 36,
      style_id: 4,
      brand_id: 3,
      condition_id: 22,
      status_id: 51,
      title: 'Vroom vroom',
      description: 'Awesome little t-shirt is seriously adorable. Give your little bundle of joy a rev up with this cute little T, its lovely and soft and perfect for summer days. Layered with a hoody or other outer layer is will be great in to autumn as well.',
      photo1: '/images/tshirt_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 197,
      size_id: 35,
      style_id: 4,
      brand_id: 4,
      condition_id: 22,
      status_id: 51,
      title: 'Little cutie',
      description: 'The title says it all, we are in love with the adorable embroidery on this top. The leaves are starting to fray in a couple of places but there is heaps of love left in this navy blue top. The colours are great and the fit is on the larger side.',
      photo1: '/images/tshirt_2.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 198,
      size_id: 34,
      style_id: 4,
      brand_id: 5,
      condition_id: 22,
      status_id: 51,
      title: 'Acute shirt',
      description: 'Geek humour at its best. Bright and cheerful yellow is perfect for this funny little top. We imagine it teamed up with jeans or a denim skirt for a mini-geek appearance. Would be great for either a boy or a girl and is in near new condition.',
      photo1: '/images/tshirt_4.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 199,
      size_id: 33,
      style_id: 4,
      brand_id: 6,
      condition_id: 22,
      status_id: 51,
      title: 'I won!',
      description: 'Funny little t-shirt, was too cute to ignore. It has a couple of little marks on it, but is still in good condition. It is not a very thick fabric, so might be best used as a layer with other clothing items.',
      photo1: 'tshirt_3.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 200,
      size_id: 31,
      style_id: 4,
      brand_id: 7,
      condition_id: 21,
      status_id: 51,
      title: 'Munch monkey',
      description: 'The yellow always makes us smile, such a sunny bright top. Cute printed monkey on the front, the paint is starting to crack and peel in places. Good size, it will fit most babies in the size range. Great for summer days.',
      photo1: '/images/tshirt_5.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 201,
      size_id: 31,
      style_id: 4,
      brand_id: 8,
      condition_id: 23,
      status_id: 51,
      title: 'One-derful',
      description: 'Oh it is so punny! If your bub got a birthday coming up... This is the perfect shirt to eat cake in. Lovely quality from this high street retailer, looks like its hardly been worn so we are putting this on our wish list for warmer months.',
      photo1: '/images/tshirt_6.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 202,
      size_id: 33,
      style_id: 4,
      brand_id: 9,
      condition_id: 23,
      status_id: 51,
      title: 'Only child',
      description: 'Cute little top with a frill. The date does kind of date the t-shirt but the added frill made it too special to ignore. The longer layer means it would work well as a little dress too it layered with thick tights or leggings.',
      photo1: '/images/tshirt_7.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 203,
      size_id: 36,
      style_id: 4,
      brand_id: 10,
      condition_id: 24,
      status_id: 51,
      title: 'Eat, Sleep ...',
      description: 'Gym junkies... this is for you! If you want to raise your self a little powerhouse baby, get your sweat on by racing to be first to borrow this t-shirt. It is slightly small in size, so might be best for little bubbas.',
      photo1: '/images/tshirt_8.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 204,
      size_id: 36,
      style_id: 4,
      brand_id: 10,
      condition_id: 24,
      status_id: 51,
      title: 'Little Sister',
      description: 'I love seeing darker colours on girls. It does not have to be pink to be super cute. This top is a little stretched but the print is in really good condition and there is still a lot of wear to be had from this little number.',
      photo1: '/images/tshirt_9.jpg'
      http://www.carters.com/dw/image/v2/AAMK_PRD/on/demandware.static/-/Sites-carters_master_catalog/default/dw8fc630f6/hi-res/235G900_Default.jpg?sw=244',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 205,
      size_id: 36,
      style_id: 4,
      brand_id: 10,
      condition_id: 24,
      status_id: 51,
      title: 'Tui cute!',
      description: 'This designer t-shirt is made of thick luxury jersey knit fabric and will fit all sizes. There is lovely print on the front which is cracked but not peeling, its been very well made and will be warm even if not layered with anything else.',
      photo1: 'https://ih0.redbubble.net/image.363492089.3102/ra%2Cbaby_tee%2Cx520%2Cbaby_blue%2Cfront-pad%2C420x460%2Cf8f8f8.lite-1u4.jp',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 206,
      size_id: 32,
      style_id: 1,
      brand_id: 1,
      condition_id: 24,
      status_id: 51,
      title: 'Dungarees',
      description: 'Do these ever go out of fashion? We love these little dungarees, they would make any kid look ready to take on the world. If clothing could shout, these would shout high energy. Perfect for your little one if they never sit still!',
      photo1: 'http://media.jojomamanbebe.com/media/catalog/product/cache/1/small_image/300x/c75b604ff82387216c03b93a91337e7c/d/2/d2783red_2.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 207,
      size_id: 32,
      style_id: 1,
      brand_id: 2,
      condition_id: 21,
      status_id: 51,
      title: 'Awesome cord',
      description: 'Great colour - classic beige with the preppy little turn up, make these pants a winner in our book. Team it up with blues and reds for a strong distinct look. Dressed to impressed you are ready, and set... Time to take on the siblings.',
      photo1: 'http://www.crecerfeliz.es/var/ezflow_site/storage/images/el-bebe/buenas-ideas/moda-primeros-meses/pantalon-bebe-chicco/2711565-1-esl-ES/pantalon-bebe-chicco_reference.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 208,
      size_id: 34,
      style_id: 1,
      brand_id: 3,
      condition_id: 22,
      status_id: 51,
      title: 'Leopard print love!',
      description: 'Seriously who can resist these. We love this print! The gold is starting to wear in places, but they are in great condition and made of a really lovely warm jersey fabric. Take these home today, because they wont last long this style is super popular.',
      photo1: 'http://do8c9c0qrr1ax.cloudfront.net/sys-master/images/hd8/hc7/9089997668382/649043_001.jpg_BNLWF_medium',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 209,
      size_id: 35,
      style_id: 1,
      brand_id: 4,
      condition_id: 23,
      status_id: 51,
      title: 'Foot coverage',
      description: 'We love these little leggings, the feet enclosed means baby will stay cosy and warm all the time. Perfect for little ones who are still learning to regulate. The grey of these is a little faded in appearance but otherwise in really good condition.',
      photo1: 'http://do8c9c0qrr1ax.cloudfront.net/sys-master/images/he3/h5f/9073076076574/538414_001.jpg_BNLWF_medium',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 210,
      size_id: 36,
      style_id: 1,
      brand_id: 5,
      condition_id: 22,
      status_id: 51,
      title: 'Homemade!',
      description: 'Holy moly! This fabric is so gorgeous. Totally on trend with the slightly baggy style. The elastic is soft and very stretchy, the seamstress who put these together really knows there craft. They are so lovely - thank you talented person for sharing them with us!',
      photo1: 'https://s-media-cache-ak0.pinimg.com/736x/38/c3/96/38c3966440cc204892b23c20837dd27c.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 211,
      size_id: 32,
      style_id: 1,
      brand_id: 6,
      condition_id: 23,
      status_id: 51,
      title: 'Raindrops',
      description: 'Awesome little track suit bottoms with lots of room for a nappy. Thick jersey so will be lovely and warm. They are very stretchy and in perfect condition. IF I could get away with wearing this style of pants every day I would... you know you would too.',
      photo1: 'https://4.imimg.com/data4/UT/TO/MY-2190204/1-250x250.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 212,
      size_id: 33,
      style_id: 11,
      brand_id: 7,
      condition_id: 24,
      status_id: 51,
      title: 'Jeans forever',
      description: '',
      photo1: '/images/pants_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 213,
      size_id: 34,
      style_id: 1,
      brand_id: 8,
      condition_id: 23,
      status_id: 51,
      title: 'I <3 Jeans',
      description: '',
      photo1: '/images/pants_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 214,
      size_id: 35,
      style_id: 1,
      brand_id: 9,
      condition_id: 21,
      status_id: 51,
      title: 'Baa-utiful',
      description: '',
      photo1: '/images/pants_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 215,
      size_id: 35,
      style_id: 1,
      brand_id: 9,
      condition_id: 21,
      status_id: 51,
      title: 'Frilly bum',
      description: '',
      photo1: '/images/pants_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 216,
      size_id: 35,
      style_id: 1,
      brand_id: 9,
      condition_id: 21,
      status_id: 51,
      title: 'Foxy!',
      description: '',
      photo1: '/images/pants_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 217,
      size_id: 35,
      style_id: 1,
      brand_id: 9,
      condition_id: 21,
      status_id: 51,
      title: 'Jeans for the win',
      description: '',
      photo1: '/images/pants_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 218,
      size_id: 35,
      style_id: 1,
      brand_id: 9,
      condition_id: 21,
      status_id: 51,
      title: 'Legs forever',
      description: '',
      photo1: '/images/pants_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 218,
      size_id: 35,
      style_id: 1,
      brand_id: 9,
      condition_id: 21,
      status_id: 51,
      title: 'Lazy sailing days',
      description: '',
      photo1: '/images/pants_1.jpg',
      photo2: '/images/photo_2.svg'
      },
      {
      id: 219,
      size_id: 35,
      style_id: 1,
      brand_id: 9,
      condition_id: 21,
      status_id: 51,
      title: 'Anchors away',
      description: '',
      photo1: '/images/pants_1.jpg',
      photo2: '/images/photo_2.svg'
      }
      ])
    })
}
